### ISSUE TITLE
 Is it suitable for Tp-Link c5v v3 v1.7_220905 given by ISP?

### ISSUE THREAD

**Issue by shortcut00** [andreasrsa/OpenWRT-Archer-C5#3]
Is it suitable for Tp-Link c5v v3 v1.7_220905 given by ISS?

**Comment by andreasrsa** [comment]
I patched the source specifically for the SoC [(https://apps.fcc.gov/oetcf/eas/reports/GenericSearchResult.cfm?RequestTimeout=500)]of the V4 and then compiled. So, no, I wouldn't think so.

**Comment by openwebkey** [comment]
thanks. would you consider for c5v?

**Comment by salihy4vuz** [comment]
> Kaynağı özellikle V4'ün SoC'si [(https://apps.fcc.gov/oetcf/eas/reports/GenericSearchResult.cfm?RequestTimeout=500)] için yamaladım ve ardından derledim. Yani, hayır, öyle düşünmezdim.

thanks. would you consider for c5v? It is a modem widely used in Turkey, Brazil, Russia, and many other countries, the c5v. because people do not have any income to buy modems other than the modem provided by the internet service provider. Don't you want to save all these people from isp's custody? if i understood software i would definitely do it

**Comment by andreasrsa** [comment]
I'm based in South Africa. We have our fair share of problems my friend. This firmware was built on the foundation of the SoC of the v4. The intended purpose was to show that one can patch System On Chip routers not supported by OpenWRT at source. 

I would suggest researching your router, and if it's got a SoC like the C5v4 Realtek SoC, search related drivers to patch the kernel at source.

Please note, I released this As Is. The firmware I built is designed for the router with a usb drive attached.

The firmware allows for the usb drive to be recognised, and for it to act as an extension of the device's limitations (memory).

All these changes are customised for the router in question.

Again, I applaud anyone who looks out the box, but I supplied this as is, and am not affiliated with OpenWRT or TP-link.

**Comment by openwebkey** [comment]
> Güney Afrika'da yaşıyorum. Sorunlardan payımıza düşeni alıyoruz dostum. Bu bellenim, v4'ün SoC'sinin temeli üzerine inşa edilmiştir. Amaç, kaynakta OpenWRT tarafından desteklenmeyen System On Chip yönlendiricilerine yama yapılabileceğini göstermekti.
> 
> Yönlendiricinizi araştırmanızı ve C5v4 Realtek SoC gibi bir SoC'ye sahipse, çekirdeği kaynağında yamalamak için ilgili sürücüleri aramanızı öneririm.
> 
> Lütfen dikkat, bunu Olduğu Gibi yayınladım. Oluşturduğum bellenim, USB sürücüsü takılı olan yönlendirici için tasarlanmıştır.
> 
> Üretici yazılımı, USB sürücüsünün tanınmasına ve cihazın sınırlamalarının (bellek) bir uzantısı olarak işlev görmesine olanak tanır.
> 
> Tüm bu değişiklikler, söz konusu yönlendirici için özelleştirilmiştir.
> 
> Yine, kutunun dışına bakan herkesi alkışlıyorum, ancak bunu olduğu gibi sağladım ve OpenWRT veya TP-link ile bağlantılı değilim.

thank you so much my bro

**Comment by salihy4vuz** [comment]
thank you so much my bro
