### ISSUE TITLE
no lan interface

### ISSUE THREAD

**Issue by Jonathan1718** [andreasrsa/OpenWRT-Archer-C5#4]
no lan interface working ... wan also

**Comment by andreasrsa** [comment]
Interesting. In the interest of transparency, I did state as is. But I also published images of the firmware after flashing.

Are you flashing from the release I posted or recompiling?

**Comment by Jonathan1718** [comment]
release you posted ... i tried another release posted on a forum and still no lan but now CLI is refusing connection ... I almost bricked the router , tried to reflash orginial firmware trough serial  got a bad checksum error... I can still access openwrt connected in wifi trough SSH

**Comment by andreasrsa** [comment]
Couple things. Obviously you read my comments? This firmware takes most of the routers memory on flash. Which is why it contains usb drivers as well as tools to recognize and partition the attached usb drive.

I would suggest you clone OpenWRT and apply the patch in the comments (12). Then build your firmware from source. When you go into build menu, your will see the tp-link. After saving cat .config and look at the build config.

**Comment by namiltd** [comment]
Some Archer c5 v4 have different version of Realtek RTL8367B chip, other than 0x0276, 0x0597, 0x6367. Unfortunately, Ethernet will not work for unlisted versions.

**Comment by andreasrsa** [comment]
> no lan interface working ... wan also

Try pulling the main openwrt repo, and following the instructions. The repo I have is primarily to show where patches end up.

**Comment by andreasrsa** [comment]
Final note here:

- Everything (et al) must be done as a non-root user. From pulling repo to your home directory to patches, to compiling.
- Don't use this repo. It's pulled from OpenWRT and out of date. Pull OpenWRT repo directly
- treat the pulled repo as your "rootdir". Ideally, pull the repo directly to /home/ for example, /home/openwrt
- I use tags, make sure you are in a tagged repo 
- run the two scripts to update source
- download the patch
- apply the patch 
- if you get no errors, yay!
- run make menuconfig
- chose the correct chipsets, if the patch was applied correctly, the C5 v5 MUST be listed and selected.
- check all kmods as "option" so the revision carries into the build. If you do not,  and then try install some, you will Definitely get mismatch errors. You will need to recompile. CHECK KMODS.
- If you want to the exfat path, strongly suggest you install all necessary modules now.

If you follow the above, and have no issues, the compilation should successfully complete.

**I provided this as is, I can try assist when a detailed query comes through. This firmware has been tested on 3 separate C5 V4 routers. We normally use EU standards, and not US**

**Comment by namiltd** [comment]
The final note should be the information that TP-Link Archer C5 v4 is available in various subversions of chipsets, not all of them are currently supported by OpenWRT.

**Comment by andreasrsa** [comment]
The whole point of this was to show that a router with a SoC, in this case,  MT7620A SoC. I do not know what you are referring to, but I am interested in knowing what chipset your  TP-Link Archer C5 v4 is running. Reply.

For reference:
https://openwrt.org/toh/hwdata/tp-link/tp-link_archer_c5_v4
https://openwrt.org/docs/techref/hardware/soc/soc.mediatek
https://wikidevi.wi-cat.ru/TP-LINK_Archer_C5_v4.x

FCC:
https://apps.fcc.gov/oetcf/eas/reports/GenericSearchResult.cfm?RequestTimeout=500

**Comment by namiltd** [comment]
Look at https://forum.openwrt.org/t/support-for-new-archer-c5-v4/15889/534 to 549
```
Currently supported and tested are versions: 0x0276, 0x0597 and 0x6367.
```

**Comment by andreasrsa** [comment]
The photo of the back of the router. Did you take it?

[](https://openwrt.org/toh/tp-link/archer_c5_v4)

[](https://openwrt.org/_detail/media/tplink/archerc5/c5_v4_hwversion.jpg?id=toh%3Atp-link%3Aarcher_c5_v4)

This is the same router. Same MediaTek MT7620A SoC.

- https://openwrt.org/docs/guide-developer/build-system/install-buildsystem#debianubuntu

Everything below is as non-root:
- git clone https://git.openwrt.org/openwrt/openwrt.git/
cd openwrt
./scripts/feeds update -a
./scripts/feeds install -a
- wget -o 4327.patch https://patch-diff.githubusercontent.com/raw/openwrt/openwrt/pull/4327.patch
- git apply 4327.patch / if you get an error, you did something wrong)
- make defconfig
- make menuconfig
- set Target System: MediaTek Ralink MIPS
- set Subtarget: MT7620..
- set Target Profile: TP-Link Archer C5 v4
- set kmod to be optional (for few kernel hash compatibility)
- add luci, and whatever else you want 
- save
- make download
- make -j4 V=s (j is the cores, the more, the faster the compilation)

The above is the process my friend. When complete, everything should be in the bin directory of my memory serves me.

Also, I did provide images of the final product 

![image](https://github.com/andreasrsa/OpenWRT-Archer-C5/assets/2247180/5699ce93-b6e8-4422-b0cd-bc70fefc1b9a)
![image](https://github.com/andreasrsa/OpenWRT-Archer-C5/assets/2247180/e573d48c-e57f-4037-ba8f-18fec5352959)
![image](https://github.com/andreasrsa/OpenWRT-Archer-C5/assets/2247180/280ea796-bcd6-48ef-824a-b3e19b8fc2bf)
![image](https://github.com/andreasrsa/OpenWRT-Archer-C5/assets/2247180/1ab52c00-a7f2-4c75-9021-2bc2ca6ecc4d)

**Comment by andreasrsa** [comment]
> Look at https://forum.openwrt.org/t/support-for-new-archer-c5-v4/15889/534 to 549
> 
> ```
> 
> Currently supported and tested are versions: 0x0276, 0x0597 and 0x6367.
> 
> ```

I had a look at your thread. Firstly, I commend you for your efforts in assisting people. It's important. You clearly have an understanding of the architecture. As well as busybox.

I'm on my iPhone, so, getting lost in the weeds here.

The thread claims it's an Archer C5v4? But the information that's spitting out is strange?

Have you recommend he install hwinfo? [see uri](https://openwrt.org/packages/pkgdata/hwinfo)

Also, personally I have found that building the firmware from a snapshot will lead to kmod issues galore. But that's down the line.
