### ISSUE TITLE
Wrong release files

### ISSUE THREAD

**Issue by namiltd** [andreasrsa/OpenWRT-Archer-C5#5]
In release v21.02.01-cstm (https://github.com/andreasrsa/OpenWRT-Archer-C5/releases/tag/v21.02.01-cstm) there are incorrect source files (zip and tar.gz). The attached files do not contain patches for the Archer A5 V4 router (e.g. mt7620a_tplink_archer-c5-v4.dts).

**Comment by andreasrsa** [comment]
Sorry - I see that. Good find!

Just download the primary .zip file, or clone this repo. https://github.com/andreasrsa/OpenWRT-Archer-C5/tree/master/target/linux/ramips/dts
